// lib/localization/app_strings.dart
import 'localization_manager.dart';

class AppStrings {
  // Private constructor
  const AppStrings._();
  
  // Language maps
  static final Map<String, dynamic> _strings = {
    'he': {
      // Home screen
      'personal_achievements': 'הישגים אישיים',
      'challenges': 'אתגרים',
      'stars': 'כוכבים',
      'my_team': 'הקבוצה שלי',
      'add_team': 'הוסף קבוצה',
      // Navigation
      'highlights': 'הישגים',
      'fan_zone': 'אוהדים',
      'home': 'בית',
      'team': 'קבוצה',
      'events': 'אירועים',
      // Placeholders
      'no_team': 'לא נמצאה קבוצה',
      'no_events': 'אין אירועים קרובים',
      'no_news': 'אין חדשות',
      'upcoming_trainings': 'אימונים קרובים',
      'team_players': 'שחקני הקבוצה',
      'my_children': 'הילדים שלי',
      'upcoming_events': 'אירועים קרובים',
      'payments': 'תשלומים',
      'my_mentees': 'החניכים שלי',
      'upcoming_sessions': 'מפגשים קרובים',
      'development_plans': 'תוכניות פיתוח',
      'my_community': 'הקהילה שלי',
      'community_teams': 'קבוצות בקהילה',
      'view_all_teams': 'צפה בכל הקבוצות',
      'announcements': 'הודעות',
      'change_language': 'החלף שפה',
      'news': 'חדשות',
      'no_teams': 'אין קבוצות',
      'participants': 'משתתפים',
      'teams': 'קבוצות',
      'members': 'חברים',
      'no_announcements': 'אין הודעות',
      'general_error': 'אירעה שגיאה, אנא נסה שוב מאוחר יותר',
      'network_error': 'אין חיבור לאינטרנט, אנא בדוק את החיבור שלך',
      'retry': 'נסה שוב',
      'dismiss': 'סגור',
      'navigation_error_title': 'שגיאת ניווט',
      'navigation_error_message': 'לא ניתן לנווט למסך המבוקש',
      'ok': 'אישור',
      'error_title': 'שגיאה',
      'go_back': 'חזור',
      'loading_profile': 'טוען פרופיל...',
      'settings': 'הגדרות', // Hebrew
      'language_settings': 'הגדרות שפה',
      'app_language': 'שפת האפליקציה',
      'appearance_settings': 'הגדרות מראה',
      'theme': 'ערכת נושא',
      'system_theme': 'לפי מערכת',
      'light_theme': 'בהיר',
      'dark_theme': 'כהה',
      'notification_settings': 'הגדרות התראות',
      'push_notifications': 'התראות פוש',
      'push_notifications_desc': 'קבל התראות על פעילויות ועדכונים',
      'email_notifications': 'התראות אימייל',
      'email_notifications_desc': 'קבל עדכונים חשובים באימייל',
      'about': 'אודות',
      'app_version': 'גרסת אפליקציה',
      'terms_of_service': 'תנאי שימוש',
      'privacy_policy': 'מדיניות פרטיות',
      'contact_us': 'צור קשר',
      'logout': 'התנתק',
      'achievement_tooltip_prefix': 'הישג: ',
      'achievement_complete': 'הושלם ב-100%',
      'view_all': 'צפה בהכל',
      'milestone': 'אבן דרך',
      'share_achievement': 'שתף הישג',
      // Achievement labels
      'achievement_goals': 'שערים',
      'achievement_training': 'אימונים',
      'achievement_matches': 'משחקים',
      'achievement_skills': 'מיומנויות',
      // Welcome Screen
      'welcome_title': 'ברוכים הבאים!',
      'join_team_button': 'הצטרפו לקבוצה!',
      'login_button': 'כניסת משתמשים',
      'welcome_info_link': 'לחצו כאן למידע נוסף על FootballHero\nותכנית HoodHero',

      // Login Screen
      'login_screen_title': 'כניסה למערכת',
      'email_label': 'דוא"ל',
      'password_label': 'סיסמה',
      'login_button_text': 'כניסה',
      'forgot_password': 'שכחת סיסמה?',
      'empty_fields_error': 'נא למלא את כל השדות',
      'invalid_credentials': 'פרטי התחברות שגויים',
      'email_not_confirmed': 'דוא"ל לא מאומת. אנא בדוק את תיבת הדואר שלך',
      'too_many_requests': 'יותר מדי ניסיונות כניסה. אנא נסה שוב מאוחר יותר',
      'login_error': 'שגיאה בהתחברות. אנא נסה שוב מאוחר יותר',

      // Signup Screen
      'signup_screen_title': 'הרשמה',
      'email_hint': 'דוא"ל',
      'password_hint': 'סיסמה',
      'confirm_password_hint': 'אימות סיסמה',
      'signup_button_text': 'יצירת חשבון',
      'invalid_email': 'אנא הזן כתובת דוא"ל תקינה',
      'passwords_not_matching': 'הסיסמאות אינן תואמות',
      'password_requirements': '8 תווים לפחות, אות גדולה, ספרה ותו מיוחד',
      'password_too_short': 'הסיסמה חייבת להיות באורך של 8 תווים לפחות',
      'password_needs_uppercase': 'הסיסמה חייבת להכיל לפחות אות גדולה אחת',
      'password_needs_number': 'הסיסמה חייבת להכיל לפחות ספרה אחת',
      'password_needs_special_char': 'הסיסמה חייבת להכיל לפחות תו מיוחד אחד',
      'terms_acceptance': 'אני מסכים/ה לתנאי השימוש',
      'user_already_registered': 'משתמש זה כבר רשום במערכת',
      'signup_unexpected_error': 'שגיאה בלתי צפויה. אנא נסה שוב מאוחר יותר',
      'signup_create_error': 'שגיאה ביצירת המשתמש. אנא נסה שוב.',
     
      // Forgot Password Screen
      'forgot_password_title': 'איפוס סיסמה',
      'forgot_password_description': 'הזן את הדוא"ל שלך ואנו נשלח קישור לאיפוס סיסמה',
      'send_reset_link': 'שלח קישור לאיפוס',
      'email_required': 'נא להזין דוא"ל',
      'invalid_email_signup': 'נא להזין כתובת דוא"ל תקינה',
      'too_many_requests_forgot_password': 'יותר מדי בקשות. אנא נסה שוב מאוחר יותר.',
      'reset_link_sent': 'הודעת איפוס סיסמה נשלחה',
      'reset_request_error': 'שגיאה בשליחת הבקשה. אנא נסה שוב.',

      // Reset Password Screen
      'reset_password_title': 'איפוס סיסמה',
      'reset_password_subtitle': 'הזן סיסמה חדשה לחשבונך',
      'new_password': 'סיסמה חדשה',
      'confirm_password': 'אישור סיסמה',
      'reset_password_button': 'אפס סיסמה',
      'token_verification_error': 'שגיאה באימות הקישור. אנא נסה לאפס סיסמה שוב.',
      'token_invalid': 'קישור האיפוס פג תוקף. אנא בקש קישור איפוס סיסמה חדש.',
      'password_reset_success': 'הסיסמה עודכנה בהצלחה!',

      // Onboarding Screen
      'onboarding_title': 'השלמת הרשמה',
      'name_label': 'שמך',
      'name_validation': 'נא להזין שם',
      'dob_label': 'תאריך לידה',
      'dob_validation': 'נא לבחור תאריך לידה',
      'user_type_label': 'סוג משתמש',
      'user_type_validation': 'נא לבחור סוג משתמש',
      'address_label': 'כתובת',
      'address_validation': 'נא להזין כתובת',
      'city_label': 'עיר',
      'city_validation': 'נא להזין עיר',
      'phone_label': 'מספר טלפון',
      'phone_hint': 'הזן מספר טלפון (לדוגמה: 050-1234567)',
      'submit_button': 'שלח',
      'cancel_registration': 'לבטל הרשמה?',
      'cancel_registration_confirm': 'האם את/ה בטוח/ה שברצונך לבטל את ההרשמה? כל הנתונים שהוזנו ימחקו',
      'no': 'לא',
      'yes': 'כן',
      'unexpected_error': 'שגיאה לא צפויה. אנא נסה שוב מאוחר יותר.',
      'user_roles': {
        'player': 'שחקן',
        'parent': 'הורה',
        'coach': 'מאמן',
        'community_manager': 'צוות קהילתי',
        'mentor': 'מנטור',
        'player_registration_title': 'שחקן - שלב ההרשמה',
        'your_team_optional': 'הקבוצה שלך: (אופציונלי)',
        'team_name': 'שם הקבוצה',
        'leave_empty_if_no_team': 'השאר/י ריק במידה ואין לך קבוצה או שהקבוצה לא נמצאת',
        'select_team_from_list': 'יש לבחור קבוצה מהרשימה',
        'position_label': 'תפקיד:',
        'position_goalkeeper': 'שער',
        'position_defense': 'הגנה',
        'position_midfield': 'קישור',
        'position_offense': 'התקפה',
        'height_label': 'גובה: ',
        'weight_label': 'משקל: ',
        'height_unit': '(בס"מ)',
        'weight_unit': '(בק"ג)',
        'enter_height': 'נא להזין גובה',
        'enter_weight': 'נא להזין משקל',
        'strong_leg': 'רגל חזקה:',
        'right_leg': 'ימין',
        'left_leg': 'שמאל',
        'select_strong_leg': 'נא לבחור רגל חזקה',
        'skill_speed': 'מהירות',
        'skill_headers': 'נגיחות',
        'skill_defending': 'הגנה',
        'skill_passing': 'מסירה',
        'skill_scoring': 'הבקעה',
        'skill_goalkeeping': 'שוערות',
        'continue_button': 'המשך',
        'team_not_found': 'הקבוצה שהוזנה לא נמצאה במערכת',
        'parent_registration_title': 'הורה - שלב ההרשמה',
        'personal_id_label': 'מספר תעודת זהות:',
        'personal_id_required': 'נא להזין מספר תעודת זהות',
        'personal_id_length': 'מספר תעודת זהות חייב להכיל 9 ספרות',
        'player_email_optional': 'אימייל השחקן (אופציונלי):',
        'leave_empty_if_no_player': 'השאר ריק אם אין שחקן משויך',
        'player_not_found': 'שחקן לא נמצא',
        'player_search_error': 'אירעה שגיאה בחיפוש השחקן',
        'verify_player_details': 'אימות פרטי השחקן',
        'confirm_player_details': 'האם אלו הפרטים הנכונים של השחקן?',
        'player_verification_cancelled': 'אימות השחקן בוטל',
        'not_available': 'לא זמין',
        'coach_registration_title': 'מאמן - שלב ההרשמה',
        'certification_status': 'סטטוס הסמכה:',
        'no_certificate': 'אין לי תעודת מאמנ/ת',
        'professional_coach': 'אני מאמנ/ת במקצועי',
        'certificate_number': 'מספר תעודה:',
        'enter_certificate_number': 'נא להזין מספר תעודה',
        'upload_certificate': 'העלאה של צילום של תעודת האימון:',
        'existing_file': 'קובץ קיים',
        'choose_file': 'בחירת קובץ',
        'file_pick_error': 'אירעה שגיאה בבחירת הקובץ. אנא נסה שוב.',
        'community_manager_registration_title': 'מנהל קהילה - שלב ההרשמה',
        'mentor_registration_title': 'מנטור - שלב ההרשמה',
        'your_community': 'הקהילה שלך:',
        'community_name': 'שם הקהילה',
        'select_community_from_list': 'יש לבחור קהילה מהרשימה',
        'leave_empty_if_no_community': 'השאר/י ריק במידה ואין לך קהילה או שהקהילה לא נמצאת',
        'community_not_found': 'הקהילה שהוזנה לא נמצאה במערכת',
        'choose_favorite_clubs': 'בחר את הקבוצות האהובות עליך',
        'search_football_club': 'חפש מועדון כדורגל',
        'selected_clubs': 'הקבוצות שבחרת:',
        'finish_registration': 'סיום ההרשמה',
        'favorites_save_error': 'שגיאה בשמירת קבוצות אהובות. אנא נסה שוב.',
        'clubs_search_error': 'שגיאה בחיפוש מועדונים. אנא נסה שוב.',
      },
    },
    'en': {
      // Home screen
        'personal_achievements': 'Personal Achievements',
        'challenges': 'Challenges',
        'stars': 'Stars',
        'my_team': 'My Team',
        'add_team': 'Add Team',
        // Navigation
        'highlights': 'Highlights',
        'fan_zone': 'Fan Zone',
        'home': 'Home',
        'team': 'Team',
        'events': 'Events',
        // Placeholders
        'no_team': 'No Team Found',
        'no_events': 'No Upcoming Events',
        'no_news': 'No News',
        'upcoming_trainings': 'Upcoming Trainings',
        'team_players': 'Team Players',
        'my_children': 'My Children',
        'upcoming_events': 'Upcoming Events',
        'payments': 'Payments',
        'my_mentees': 'My Mentees',
        'upcoming_sessions': 'Upcoming Sessions',
        'development_plans': 'Development Plans',
        'my_community': 'My Community',
        'community_teams': 'Community Teams',
        'view_all_teams': 'View All Teams',
        'announcements': 'Announcements',
        'change_language': 'Change Language',
        'news': 'News',
        'no_teams': 'No Teams',
        'participants': 'participants',
        'teams': 'teams',
        'members': 'members',
        'no_announcements': 'No Announcements',
        'general_error': 'An error occurred, please try again later',
        'network_error': 'No internet connection, please check your connection',
        'retry': 'Retry',
        'dismiss': 'Dismiss',
        'navigation_error_title': 'Navigation Error',
        'navigation_error_message': 'Unable to navigate to the requested screen',
        'ok': 'OK',
        'error_title': 'Error',
        'go_back': 'Go Back',
        'loading_profile': 'Loading profile...', 
        'settings': 'Settings',
        'language_settings': 'Language Settings',
        'app_language': 'App Language',
        'appearance_settings': 'Appearance Settings',
        'theme': 'Theme',
        'system_theme': 'System Default',
        'light_theme': 'Light',
        'dark_theme': 'Dark',
        'notification_settings': 'Notification Settings',
        'push_notifications': 'Push Notifications',
        'push_notifications_desc': 'Receive notifications for activities and updates',
        'email_notifications': 'Email Notifications',
        'email_notifications_desc': 'Receive important updates via email',
        'about': 'About',
        'app_version': 'App Version',
        'terms_of_service': 'Terms of Service',
        'privacy_policy': 'Privacy Policy',
        'contact_us': 'Contact Us',
        'logout': 'Logout',
        'achievement_tooltip_prefix': 'Achievement: ',
        'achievement_complete': '100% Complete',
        'view_all': 'View All',
        'milestone': 'Milestone',
        'share_achievement': 'Share Achievement',
        // Achievement labels
        'achievement_goals': 'Goals',
        'achievement_training': 'Training',
        'achievement_matches': 'Matches',
        'achievement_skills': 'Skills',
        // Welcome Screen
        'welcome_title': 'Welcome!',
        'join_team_button': 'Join the Team!',
        'login_button': 'User Login',
        'welcome_info_link': 'Click here for more information about FootballHero\nand HoodHero Program',

        // Login Screen
        'login_screen_title': 'Login to System',
        'email_label': 'Email',
        'password_label': 'Password',
        'login_button_text': 'Login',
        'forgot_password': 'Forgot Password?',
        'empty_fields_error': 'Please fill in all fields',
        'invalid_credentials': 'Invalid login credentials',
        'email_not_confirmed': 'Email not confirmed. Please check your inbox',
        'too_many_requests': 'Too many login attempts. Please try again later',
        'login_error': 'Error logging in. Please try again later',

        // Signup Screen
        'signup_screen_title': 'Sign Up',
        'email_hint': 'Email',
        'password_hint': 'Password',
        'confirm_password_hint': 'Confirm Password',
        'signup_button_text': 'Create Account',
        'invalid_email': 'Please enter a valid email address',
        'passwords_not_matching': 'Passwords do not match',
        'password_requirements': 'At least 8 characters, uppercase letter, number, and special character',
        'password_too_short': 'Password must be at least 8 characters long',
        'password_needs_uppercase': 'Password must contain at least one uppercase letter',
        'password_needs_number': 'Password must contain at least one number',
        'password_needs_special_char': 'Password must contain at least one special character',
        'terms_acceptance': 'I agree to the Terms of Service',
        'user_already_registered': 'This user is already registered in the system',
        'signup_unexpected_error': 'An unexpected error occurred. Please try again later',
        'signup_create_error': 'Error creating user. Please try again.',

        // Forgot Password Screen
        'forgot_password_title': 'Reset Password',
        'forgot_password_description': 'Enter your email and we will send a reset link',
        'send_reset_link': 'Send Reset Link',
        'email_required': 'Please enter an email',
        'invalid_email_signup': 'Please enter a valid email address',
        'too_many_requests_forgot_password': 'Too many requests. Please try again later.',
        'reset_link_sent': 'Password reset link sent',
        'reset_request_error': 'Error sending request. Please try again.',

        // Reset Password Screen
        'reset_password_title': 'Reset Password',
        'reset_password_subtitle': 'Enter a new password for your account',
        'new_password': 'New Password',
        'confirm_password': 'Confirm Password',
        'reset_password_button': 'Reset Password',
        'token_verification_error': 'Error verifying link. Please try to reset password again.',
        'token_invalid': 'Reset link has expired. Please request a new reset link.',
        'password_reset_success': 'Password updated successfully!',

        // Onboarding Screen
        'onboarding_title': 'Complete Registration',
        'name_label': 'Your Name',
        'name_validation': 'Please enter a name',
        'dob_label': 'Date of Birth',
        'dob_validation': 'Please select a date of birth',
        'user_type_label': 'User Type',
        'user_type_validation': 'Please select a user type',
        'address_label': 'Address',
        'address_validation': 'Please enter an address',
        'city_label': 'City',
        'city_validation': 'Please enter a city',
        'phone_label': 'Phone Number',
        'phone_hint': 'Enter phone number (e.g.: 050-1234567)',
        'submit_button': 'Submit',
        'cancel_registration': 'Cancel Registration?',
        'cancel_registration_confirm': 'Are you sure you want to cancel registration? All entered data will be deleted',
        'no': 'No',
        'yes': 'Yes',
        'unexpected_error': 'An unexpected error occurred. Please try again later.',
        'user_roles': {
          'player': 'Player',
          'parent': 'Parent',
          'coach': 'Coach',
          'community_manager': 'Community Team',
          'mentor': 'Mentor'
        },
        'player_registration_title': 'Player - Registration Step',
        'your_team_optional': 'Your Team: (Optional)',
        'team_name': 'Team Name',
        'leave_empty_if_no_team': 'Leave empty if you don\'t have a team or can\'t find it',
        'select_team_from_list': 'Please select a team from the list',
        'position_label': 'Position:',
        'position_goalkeeper': 'Goalkeeper',
        'position_defense': 'Defense',
        'position_midfield': 'Midfield',
        'position_offense': 'Offense',
        'height_label': 'Height: ',
        'weight_label': 'Weight: ',
        'height_unit': '(cm)',
        'weight_unit': '(kg)',
        'enter_height': 'Please enter height',
        'enter_weight': 'Please enter weight',
        'strong_leg': 'Strong Leg:',
        'right_leg': 'Right',
        'left_leg': 'Left',
        'select_strong_leg': 'Please select strong leg',
        'skill_speed': 'Speed',
        'skill_headers': 'Headers',
        'skill_defending': 'Defending',
        'skill_passing': 'Passing',
        'skill_scoring': 'Scoring',
        'skill_goalkeeping': 'Goalkeeping',
        'continue_button': 'Continue',
        'team_not_found': 'The entered team was not found in the system',
        'parent_registration_title': 'Parent - Registration Step',
        'personal_id_label': 'ID Number:',
        'personal_id_required': 'Please enter an ID number',
        'personal_id_length': 'ID number must contain 9 digits',
        'player_email_optional': 'Player Email (Optional):',
        'leave_empty_if_no_player': 'Leave empty if no player is associated',
        'player_not_found': 'Player not found',
        'player_search_error': 'An error occurred while searching for the player',
        'verify_player_details': 'Verify Player Details',
        'confirm_player_details': 'Are these the correct player details?',
        'player_verification_cancelled': 'Player verification was cancelled',
        'not_available': 'Not available',
        'coach_registration_title': 'Coach - Registration Step',
        'certification_status': 'Certification Status:',
        'no_certificate': 'I don\'t have a coaching certificate',
        'professional_coach': 'I am a professional coach',
        'certificate_number': 'Certificate Number:',
        'enter_certificate_number': 'Please enter certificate number',
        'upload_certificate': 'Upload a copy of your coaching certificate:',
        'existing_file': 'Existing File',
        'choose_file': 'Choose File',
        'file_pick_error': 'An error occurred while selecting the file. Please try again.',
        'community_manager_registration_title': 'Community Manager - Registration Step',
        'mentor_registration_title': 'Mentor - Registration Step',
        'your_community': 'Your Community:',
        'community_name': 'Community Name',
        'select_community_from_list': 'Please select a community from the list',
        'leave_empty_if_no_community': 'Leave empty if you don\'t have a community or can\'t find it',
        'community_not_found': 'The entered community was not found in the system',
        'choose_favorite_clubs': 'Choose Your Favorite Clubs',
        'search_football_club': 'Search for football club',
        'selected_clubs': 'Selected Clubs:',
        'finish_registration': 'Complete Registration',
        'favorites_save_error': 'Error saving favorite clubs. Please try again.',
        'clubs_search_error': 'Error searching for clubs. Please try again.',
      },
    };
  
  // Get translated string based on current locale
  static String get(String key) {
    final locale = LocalizationManager().currentLocale.languageCode;
    
    // Handle nested keys like 'user_roles.player'
    if (key.contains('.')) {
      final parts = key.split('.');
      dynamic value = _strings[locale];
      for (var part in parts) {
        value = value?[part];
      }
      return value ?? key;
    }
    
    return _strings[locale]?[key] ?? _strings['en']?[key] ?? key;
  }
}