name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: latest  # Or replace with the version you're using
        channel: stable


    - name: Install Dependencies
      run: flutter pub get

    - name: Run Integration Tests
      run: flutter drive --target=test_driver/app.dart
