name: football_hero
description: A new Flutter project for managing football data.
publish_to: 'none' # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.7 
  path_provider: ^2.0.13
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  sentry_flutter: ^8.11.2
  gotrue: ^2.11.1
  file_picker: ^9.0.2  # For selecting files
  image_picker: ^1.0.7  # For image picking functionality
  go_router: ^14.8.1  # ✅ The routing package we are using
  logging: ^1.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/logo.webp
    - assets/images/logoS.webp
    - assets/images/welcomeBackground.webp
    - assets/images/mainBackground.webp

  fonts:
    - family: RubikDirt # Secondary font for Buttons or Containers Text
      fonts:
        - asset: assets/fonts/RubikDirt-Regular.ttf
    - family: VarelaRound # Main Font
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf

# Moved flutter_launcher_icons to root level
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/android/playstore.png"
  adaptive_icon_background: "#4CAF50"  # Green background color from logo
  adaptive_icon_foreground: "assets/icon/android/mdpi.png"