name: football_hero
description: A new Flutter project for managing football data.
publish_to: 'none' # Prevent accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.7 
  path_provider: ^2.0.13
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/logo.png
    - assets/images/welcomeBackground.webp
  fonts:
    - family: RubikDirt # Secondery font for Buttons or Containers Text
      fonts:
        - asset: assets/fonts/RubikDirt-Regular.ttf
    - family: VarelaRound # Main Font
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
