name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Update gradle configuration
        run: |
          cd android
          echo "org.gradle.java.home=" > local.properties
      
      - name: Build APK (Debug)
        run: flutter build apk --debug