name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK (Debug)
        run: flutter build apk --debug
      
      # Use a different version of the upload-artifact action
      - name: Upload APK
        uses: actions/upload-artifact@v2  # Changed from v3 to v2
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
"@