name: Community Manager Functions Tests

on: [push, pull_request]

jobs:
  community_manager_functions_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: latest
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run Community Manager Functions Tests
        run: flutter test test/roles/community_manager/
