name: Parent Functions Tests

on: [push, pull_request]

jobs:
  parent_functions_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Parent Functions Tests
        run: flutter test test/roles/parent/
