name: Scheduled Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'  
  workflow_dispatch:  

jobs:
  dependency_updates:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Check for outdated packages
        run: |
          mkdir -p dependency-reports
          flutter pub outdated --json > dependency-reports/outdated_packages.json || echo "Failed to check outdated packages" > dependency-reports/outdated_packages.txt
      
      - name: Analyze dependency conflicts
        run: |
          flutter pub deps > dependency-reports/dependency_tree.txt || echo "Failed to generate dependency tree" > dependency-reports/dependency_tree.txt
      
      - name: Check package vulnerabilities
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator > dependency-reports/vulnerability_report.txt || echo "Vulnerability check failed" > dependency-reports/vulnerability_report.txt
      
      - name: Upload dependency reports
        uses: actions/upload-artifact@v3
        with:
          name: dependency-reports
          path: dependency-reports/
          retention-days: 30
      
      - name: Create issue for outdated dependencies
        if: success()
        continue-on-error: true
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Weekly Dependency Update Report
          content-filepath: dependency-reports/outdated_packages.json
          labels: maintenance, dependencies

