name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Security Tests
      run: flutter test --tags=security
